### ISSUE TITLE
update amms/bonding for Scrypto v0.4.0

### ISSUE THREAD

**Issue by devmannic** [radixdlt/community-scrypto-examples#77]
I'm on it, but this might take a little while... :)

* dependencies:
  * [x] scrypto_statictypes support for Scrypto v0.4
  * [x] scrypto-unit support for Scrypto v0.4
* [x] bump dependencies in Cargo.toml
* [x] renames
* [x] auth/instantiation and potential trait macro breakage
* [ ] utilize vault proofs (see about putting back test removed in v0.3)
* [x] integration testing changes

**Comment by 0xOmarA** [comment]
Haha that was quick! We'll be waiting don't worry about it :D
